//=============================================================================
//
//   File : C3WorkspacePropertiesWidgetFileHeader.cpp
//   Creation Date : mer 11 nov 2015 06:55:28
//   Project : Code 3
//   Author : Szymon Tomasz Stefanek <sts at pragmaware dot net>
//
//   This file is part of the Code 3 Editor distribution
//   Copyright (C) 2015-2019 Szymon Tomasz Stefanek <sts at pragmaware dot net>
//
//   This program is FREE software. You can redistribute it and/or
//   modify it under the terms of the GNU General Public License
//   as published by the Free Software Foundation; either version 3
//   of the License, or (at your option) any later version.
//
//=============================================================================

#include "C3WorkspacePropertiesWidgetFileHeader.h"

#include "C3Workspace.h"

class C3WorkspacePropertiesWidgetFileHeaderPrivate
{
public:

};

#define _p m_pC3WPWFH

C3WorkspacePropertiesWidgetFileHeader::C3WorkspacePropertiesWidgetFileHeader(QWidget * pParent)
	: C3OptionsWidget(__tr("File Header"),pParent)
{
	_p = new C3WorkspacePropertiesWidgetFileHeaderPrivate();

	C3Workspace * w = C3Workspace::currentWorkspace();

	addTextEditor(__tr("The header to be added to new files. Can contain %%author%%, %%email%%, %%filename%%, %%date%% and %%project%% macros.  Do not include comment marks as they will be autogenerated."),w->fileHeaderOption());
}

C3WorkspacePropertiesWidgetFileHeader::~C3WorkspacePropertiesWidgetFileHeader()
{
	delete _p;
}

