#ifndef _c3_sysconfig_h_
#define _c3_sysconfig_h_
//=============================================================================
//
// System dependant configuration for Code3
// This file is automatically generated: do not edit
//
//=============================================================================

#define SYSTEM_SIZE_OF_SHORT_INT ${CMAKE_SYSTEM_SIZE_OF_SHORT_INT}
#define SYSTEM_SIZE_OF_INT ${CMAKE_SYSTEM_SIZE_OF_INT}
#define SYSTEM_SIZE_OF_LONG_INT ${CMAKE_SYSTEM_SIZE_OF_LONG_INT}
#define SYSTEM_SIZE_OF_LONG_LONG_INT ${CMAKE_SYSTEM_SIZE_OF_LONG_LONG_INT}

#cmakedefine COMPILE_DEBUG_MODE 1

#define COMPILE_USE_STANDALONE_MOC_SOURCES 1

#define C3_VERSION_RELEASE "${CMAKE_C3_VERSION_RELEASE}"
#define C3_VERSION_BRANCH "${CMAKE_C3_VERSION_BRANCH}"
#define C3_VERSION_CODENAME "${CMAKE_C3_VERSION_CODENAME}"

// Code3 detects the modules directory on macs/win32 by itself
// this seems to be used on linux only
#if !(defined(Q_OS_MACX) || defined(MINGW) || defined(MSVC))
#define C3_RESOURCES_DIR "${CMAKE_C3_RESOURCES_DIR}"
#define C3_MODULES_DIR "${CMAKE_C3_MODULES_DIR}"
#endif

#endif //!_c3_sysconfig_h_
