//=============================================================================
//
//   File : C3SettingsWidgetFileHeader.cpp
//   Creation Date : mer 11 nov 2015 06:40:27
//   Project : Code 3
//   Author : Szymon Tomasz Stefanek <sts at pragmaware dot net>
//
//   This file is part of the Code 3 Editor distribution
//   Copyright (C) 2015-2019 Szymon Tomasz Stefanek <sts at pragmaware dot net>
//
//   This program is FREE software. You can redistribute it and/or
//   modify it under the terms of the GNU General Public License
//   as published by the Free Software Foundation; either version 3
//   of the License, or (at your option) any later version.
//
//=============================================================================

#include "C3SettingsWidgetFileHeader.h"

#include "C3Settings.h"

class C3SettingsWidgetFileHeaderPrivate
{
public:

};

#define _p m_pC3SWFH

C3SettingsWidgetFileHeader::C3SettingsWidgetFileHeader(const QString &szLabel,QWidget * pParent)
	: C3OptionsWidget(szLabel,pParent)
{
	_p = new C3SettingsWidgetFileHeaderPrivate();

	C3Settings * pOptions = C3Settings::instance();

	addTextEditor(__tr("The header to be added to new files. Can contain %%author%%, %%email%%, %%filename%%, %%date%% and %%project%% macros and can be overridden in the workspace settings. Do not include comment marks as they will be autogenerated."),pOptions->fileHeaderOption());
}

C3SettingsWidgetFileHeader::~C3SettingsWidgetFileHeader()
{
	delete _p;
}

