#ifndef _C3TextEditorModeCPPMemberFunctionGenerator_h_
#define _C3TextEditorModeCPPMemberFunctionGenerator_h_
//=============================================================================
//
//   File : C3TextEditorModeCPPMemberFunctionGenerator.h
//   Creation Date : 2016/09/13 00:57:33
//   Project : Code 3
//   Author : Szymon Tomasz Stefanek <sts at pragmaware dot net>
//
//   This file is part of the Code 3 Editor distribution
//   Copyright (C) 2015-2019 Szymon Tomasz Stefanek <sts at pragmaware dot net>
//
//   This program is FREE software. You can redistribute it and/or
//   modify it under the terms of the GNU General Public License
//   as published by the Free Software Foundation; either version 3
//   of the License, or (at your option) any later version.
//
//=============================================================================

#include "c3_config.h"

#include <QString>

#include "C3Symbol.h"
#include "C3TextEditorModeCPPMemberGenerator.h"

class C3TextEditorModeCPPMemberFunctionGeneratorPrivate;
class C3TextEditor;
class C3SymbolManagerClassDescription;

class C3TextEditorModeCPPMemberFunctionGenerator : public C3TextEditorModeCPPMemberGenerator
{
public:

	class Settings
	{
	public:
		QString szReturnType;
		QString szFunctionName;
		QString szParameters;
		QString szBody; // if empty is autogenerated
		QString szComment; // one line!
		
		bool bIsConst;
		bool bIsVirtual;
		bool bIsStatic;
		
		C3Symbol::AccessLevel eAccessLevel;
		
		Location eLocation;
		C3SymbolManagerClassDescription * pClassDescription;
		
	public:
		Settings()
		{
			bIsConst = false;
			bIsVirtual = false;
			bIsStatic = false;
			eAccessLevel = C3Symbol::AccessLevelPublic;
			eLocation = C3TextEditorModeCPPMemberGenerator::InContextContainerDeclaration;
			pClassDescription = NULL;
		}
	};

public:
	C3TextEditorModeCPPMemberFunctionGenerator(C3TextEditor * pEditor,Settings * pSettings);
	~C3TextEditorModeCPPMemberFunctionGenerator();

public:
	bool run();

	bool insertMemberFunction(
			const QString &szComment,
			const QString &szDeclarationPrefix,
			const QString &szReturn,
			const QString &szSignature,
			const QString &szBody,
			C3Symbol::AccessLevel eAccessLevel
		);
	
private:
	C3TextEditorModeCPPMemberFunctionGeneratorPrivate * m_pC3TEMCPPMG;

}; // class C3TextEditorModeCPPMemberFunctionGenerator

#endif //!_C3TextEditorModeCPPMemberFunctionGenerator_h_